### ISSUE TITLE
allowUnknownOption seems to be not working at 13.1.0

### ISSUE THREAD

**Issue by finom** [tj/commander.js#2324]
I have the following code that I copied straight from **node_modules** after some modifications.

```ts
const program = new Command();
program.name('vovk').description('Vovk CLI').version(packageJSON.version);
initProgram(program.command('init'));
console.log('foo'); // executed
program
    .command('dev')
    .option('--next-dev', 'start schema watcher and Next.js with automatic port allocation')
    .option('--exit', 'kill the processe when schema and client is generated')
    .allowUnknownOption(true)
    .action(async (options, command) => {
      console.log('bar') // never executed
    });
```

After upgrading from 12.1.0 I started to receive `error: too many arguments for 'dev'. Expected 0 arguments but got 1.` when I run NPM script that's defined as `vovk dev --next-dev -- --turbo`

Downgrading back to 12.1.0 masked the problem. Would be great if you can give me an advice on how to solve the problem with the new version, or provide a fix in the next version. Thank you.

**Comment by shadowspawn** [comment]
Hmm, it might be appropriate to disable the error for unexpected positional arguments if `allowUnknownOption` is true, since from the point of view of the end-user of the program they are just options and not positional arguments.

To explore a quick work-around for your case, you are doing two things in the example code to allow extra unknown options:
1) calling `allowUnknownOption()`, obviously
2) using the `--` to stop option processing in the call `vovk dev --next-dev -- --turbo`

I don't think you need the `allowUnknownOption` if you are going to "escape" the unknown options using `--`, but I'll confirm that later.

In terms of your CLI, what is the `--turbo`? Does the end user consider it an option for `vovk` (that Commander does not know about), or does the end-user consider it an option for `vovk` to pass through to another program?

**Comment by shadowspawn** [comment]
The intended fix is that you declare the arguments your command accepts. For example:

```js
program
    .command('dev')
    .argument('[args...]', 'extra arguments for the dev command') // <-- add this line
```

```console
$  node index.js dev --help
foo
Usage: vovk dev [options] [args...]

Arguments:
  args        extra arguments for the dev command

Options:
  --next-dev  start schema watcher and Next.js with automatic port allocation
  --exit      kill the processe when schema and client is generated
  -h, --help  display help for command
```

**Comment by finom** [comment]
@shadowspawn thank you for quick response.

The idea behind `vovk dev --next-dev -- --turbo` is that `vovk dev --next-dev` also runs `next dev` (Next.js dev server) and passes the rest arguments to the original `next dev` command using `concurrently` API: `next dev --turbo`

I've applied the approach you've described and this is what it looks now:

```ts
  .argument('[nextArgs...]', 'extra arguments for the dev command')
  .option('--next-dev', 'start schema watcher and Next.js with automatic port allocation')
  .option('--exit', 'kill the processe when schema and client is generated')
  .action(async (nextArgs: string[], options: DevOptions, command: Command) => {
    console.log('options', nextArgs, options, command);
```

It works well! Thank you!
